# Generated by Django 3.1.7 on 2021-03-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='contacts',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
